class Destination {
  final String province;
  final String name;
  final double price;
  bool isSaved;

  Destination({
    required this.province,
    required this.name,
    required this.price,
    this.isSaved = false
  });
}

final List<Destination> destinations = [
  Destination(
      province: 'Hà Nội', name: 'Văn Miếu - Quốc Tử Giám', price: 500000),
  Destination(province: 'Hà Nội', name: 'Chùa Một Cột', price: 200000),
  Destination(province: 'Hà Nội', name: 'Hoàn Kiếm Lake', price: 0),
  Destination(
      province: 'Hà Nội', name: 'Bảo tàng Dân tộc học Việt Nam', price: 300000),
  Destination(province: 'Hà Nội', name: 'Lăng Chủ tịch Hồ Chí Minh', price: 0),
  Destination(province: 'Hà Nội', name: 'Phố cổ Hà Nội', price: 0),
  Destination(
      province: 'Hà Nội', name: 'Tháp Rùa - Đền Ngọc Sơn', price: 200000),
  Destination(province: 'Hà Nội', name: 'Làng cổ đường Lâm', price: 0),
  Destination(province: 'Hà Nội', name: 'Hồ Quan Sơn', price: 200000),
  Destination(province: 'Hà Nội', name: 'Khu du lịch Đồng Mô', price: 300000),
  Destination(
      province: 'Hà Nội', name: 'Khu sinh thái Chùa Trầm', price: 400000),
  Destination(province: 'Hà Nội', name: 'Hàm Lợn', price: 500000),
  Destination(province: 'Hà Nội', name: 'Khu sinh thái Ba Vì', price: 1000000),
  Destination(province: 'Hà Nội', name: 'My Hill Sóc Sơn', price: 7000000),
  Destination(province: 'Hà Nội', name: 'Đền Gióng', price: 200000),
  Destination(province: 'Hà Nội', name: 'Làng văn hóa 54 dân tộc', price: 0),
  Destination(province: 'Hà Nội', name: 'Vườn quốc gia Ba Vì', price: 400000),
  Destination(province: 'Hà Nội', name: 'Đền Bà Chúa Kho', price: 500000),
  Destination(province: 'Hà Nội', name: 'Làng gốm Bát Tràng', price: 0),
  Destination(province: 'Hà Nội', name: 'Chùa Hương', price: 500000),
  Destination(province: 'Đà Nẵng', name: 'Bà Nà Hill', price: 5000000),
  Destination(province: 'Đà Nẵng', name: 'Cầu Vàng', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Ngũ Hành Sơn', price: 200000),
  Destination(province: 'Đà Nẵng', name: 'Bán đảo Sơn Trà', price: 400000),
  Destination(province: 'Đà Nẵng', name: 'Công viên Biển Đông', price: 0),
  Destination(
      province: 'Đà Nẵng', name: 'Suối khoáng nóng Thần Tài', price: 300000),
  Destination(province: 'Đà Nẵng', name: 'Giếng trời', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Cầu Tình Yêu', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Làng hoa tình yêu', price: 0),
  Destination(
      province: 'Đà Nẵng', name: 'Công viên Châu Á Asia Park', price: 500000),
  Destination(province: 'Đà Nẵng', name: 'Fantasy Park', price: 400000),
  Destination(province: 'Đà Nẵng', name: 'Bãi biển Mỹ Khê', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Bãi biển Xuân Thiều', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Bãi biển Nam Ô', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Bãi tắm Non Nước', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Cầu Rồng', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Cầu Trần Thị Lý', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Cầu Sông Hàn', price: 0),
  Destination(province: 'Đà Nẵng', name: 'Cầu Thuận Phước', price: 0),
  Destination(province: 'Hồ Chí Minh', name: 'Thảo Cầm Viên', price: 500000),
  Destination(
      province: 'Hồ Chí Minh', name: 'Bảo tàng Mỹ thuật TP.HCM', price: 400000),
  Destination(
      province: 'Hồ Chí Minh', name: 'Nhà thờ Đức Bà Sài Gòn', price: 0),
  Destination(province: 'Hồ Chí Minh', name: 'Dinh Độc Lập', price: 400000),
  Destination(province: 'Hồ Chí Minh', name: 'Chợ Bến Thành', price: 0),
  Destination(province: 'Hồ Chí Minh', name: 'Phố đi bộ Nguyễn Huệ', price: 0),
  Destination(province: 'Hồ Chí Minh', name: 'Công viên Tao Đàn', price: 0),
  Destination(
      province: 'Hồ Chí Minh', name: 'Khu du lịch Văn Thánh', price: 200000),
  Destination(province: 'Hồ Chí Minh', name: 'Chùa Ngọc Hoàng', price: 0),
  Destination(province: 'Hồ Chí Minh', name: 'Hồ Con Rùa', price: 0),
  Destination(
      province: 'Hồ Chí Minh',
      name: 'Bảo tàng Lịch sử Việt Nam',
      price: 400000),
  Destination(province: 'Hải Phòng', name: 'Bãi tắm Đồi Dương', price: 0),
  Destination(province: 'Hải Phòng', name: 'Bảo tàng Hải Phòng', price: 200000),
  Destination(province: 'Hải Phòng', name: 'Cầu Niệm', price: 0),
  Destination(province: 'Hải Phòng', name: 'Công viên Hoàng Văn Thụ', price: 0),
  Destination(province: 'Hải Phòng', name: 'Đền Đồng', price: 0),
  Destination(province: 'Hải Phòng', name: 'Đền Kiến Thiết', price: 0),
  Destination(province: 'Hải Phòng', name: 'Đền Kỳ Đồng', price: 0),
  Destination(province: 'Hải Phòng', name: 'Đình Bảng', price: 0),
  Destination(province: 'Hải Phòng', name: 'Đình Kênh Dương', price: 0),
  Destination(province: 'Hải Phòng', name: 'Đình Kênh Sét', price: 0),
  Destination(
      province: 'Hải Phòng',
      name: 'Khu di tích Đình Làng Việt Kiều Châu Âu',
      price: 5000),
  Destination(province: 'Hải Phòng', name: 'Khu di tích Vua Ba', price: 100000),
  Destination(province: 'Hải Phòng', name: 'Lăng Bác Hồ Hải Phòng', price: 0),
  Destination(
      province: 'Hải Phòng', name: 'Lăng Tổng Thống Trần Đại Quang', price: 0),
  Destination(
      province: 'Hải Phòng', name: 'Nhà thờ Cửa Bắc Hải Phòng', price: 0),
  Destination(province: 'Hải Phòng', name: 'Phố cổ Hải Phòng', price: 0),
  Destination(province: 'Hải Phòng', name: 'Tháp Bà Đen', price: 0),
  Destination(province: 'Hải Phòng', name: 'Vườn động vật', price: 200000),
  Destination(province: 'Quảng Ninh', name: 'Vịnh Hạ Long', price: 1500000),
  Destination(province: 'Quảng Ninh', name: 'Đảo Tuần Châu', price: 300000),
  Destination(province: 'Quảng Ninh', name: 'Chùa Long Tuyền', price: 0),
  Destination(province: 'Quảng Ninh', name: 'Công viên Hoa Vàng', price: 0),
  Destination(
      province: 'Quảng Ninh', name: 'Bảo tàng Quảng Ninh', price: 200000),
  Destination(province: 'Quảng Ninh', name: 'Cầu Bãi Cháy', price: 0),
  Destination(province: 'Quảng Ninh', name: 'Thiên Cung Động', price: 1000000),
  Destination(province: 'Quảng Ninh', name: 'Bãi Cháy', price: 0),
  Destination(province: 'Quảng Ninh', name: 'Đền Quan Lạn', price: 0),
  Destination(
      province: 'Quảng Ninh', name: 'Vườn quốc gia Bái Tử Long', price: 200000),
  Destination(province: 'Hải Dương', name: 'Làng gốm Thanh Hà', price: 200000),
  Destination(province: 'Hải Dương', name: 'Chùa Keo', price: 0),
  Destination(
      province: 'Hải Dương',
      name: 'Vườn quốc gia Côn Sơn - Kiếp Bạc',
      price: 150000),
  Destination(province: 'Hải Dương', name: 'Đền thờ Ngô Quyền', price: 0),
  Destination(province: 'Hải Dương', name: 'Làng hoa An Phụ', price: 200000),
  Destination(province: 'Hải Dương', name: 'Tháp Rùa Hải Dương', price: 0),
  Destination(province: 'Hải Dương', name: 'Làng quê An Phú', price: 150000),
  Destination(province: 'Hải Dương', name: 'Vườn hoa Quang Trung', price: 0),
  Destination(province: 'Hải Dương', name: 'Làng sen Đại Bái', price: 250000),
  Destination(province: 'Hải Dương', name: 'Chùa Thiên Phúc', price: 0),
  Destination(province: 'Hà Giang', name: 'Cột Cờ Lũng Cú', price: 0),
  Destination(province: 'Hà Giang', name: 'Phố cổ Đồng Văn', price: 0),
  Destination(province: 'Hà Giang', name: 'Đèo Mã Pí Lèng', price: 500000),
  Destination(
      province: 'Hà Giang', name: 'Thị trấn Phó Bảng – Yên Minh', price: 0),
  Destination(province: 'Hà Giang', name: 'Rừng thông Yên Minh', price: 0),
  Destination(province: 'Hà Giang', name: 'Thung Lũng Sủng Là', price: 0),
  Destination(
      province: 'Hà Giang',
      name: 'Dinh thự Họ Vương – Biệt thự Vua Mèo',
      price: 0),
  Destination(province: 'Hà Giang', name: 'Núi Quản Bạ', price: 0),
  Destination(province: 'Hà Giang', name: 'Chợ Lùi', price: 0),
  Destination(province: 'Hà Giang', name: 'Hoàng Su Phì', price: 0),
  Destination(province: 'Hà Giang', name: 'Núi Cấm Sơn', price: 0),
  Destination(province: 'Hà Giang', name: 'Thác Yên Bình', price: 300000),
  Destination(province: 'Cao Bằng', name: 'Động Ngườm Ngao', price: 200000),
  Destination(province: 'Cao Bằng', name: 'Thác Bản Giốc', price: 500000),
  Destination(province: 'Cao Bằng', name: 'Lũng Luông', price: 0),
  Destination(province: 'Cao Bằng', name: 'Phia Đén', price: 0),
  Destination(province: 'Cao Bằng', name: 'Khu di tích Anh Kim Đồng', price: 0),
  Destination(province: 'Cao Bằng', name: 'Di tích Pắc Bó', price: 0),
  Destination(province: 'Cao Bằng', name: 'Hồ Thang Hen', price: 0),
  Destination(
      province: 'Cao Bằng',
      name: 'Di tích chiến thắng chiến dịch biên giới 1950',
      price: 0),
  Destination(
      province: 'Cao Bằng',
      name: 'Khu di tích Quốc gia đặc biệt rừng Trần Hưng Đạo',
      price: 0),
  Destination(province: 'Tuyên Quang', name: 'Núi Pắc Ta', price: 0),
  Destination(province: 'Tuyên Quang', name: 'Đền Thương', price: 0),
  Destination(province: 'Tuyên Quang', name: 'Đền Hạ', price: 0),
  Destination(province: 'Tuyên Quang', name: 'Thác Pác Ban', price: 400000),
  Destination(
      province: 'Tuyên Quang', name: 'Suối khoáng Mỹ Lâm', price: 300000),
  Destination(province: 'Tuyên Quang', name: 'Thác Mơ', price: 500000),
  Destination(
      province: 'Tuyên Quang', name: 'Vườn Hoa Lê Hồng Thái', price: 200000),
  Destination(
      province: 'Tuyên Quang',
      name: 'Khu du lịch sinh thái Thác Lăn',
      price: 400000),
  Destination(
      province: 'Tuyên Quang',
      name: 'Khu du lịch sinh thái Hàm Yên',
      price: 200000),
  Destination(
      province: 'Tuyên Quang',
      name: 'Khu du lịch sinh thái Nà Hàng',
      price: 3000000),
  Destination(province: 'Vĩnh Phúc', name: 'Hồ Đại Lải', price: 7000000),
  Destination(province: 'Vĩnh Phúc', name: 'Làng hoa Mê Linh', price: 0),
  Destination(province: 'Vĩnh Phúc', name: 'Tháp Bình Sơn', price: 0),
  Destination(province: 'Vĩnh Phúc', name: 'Cụm đình Tam Canh', price: 0),
  Destination(province: 'Vĩnh Phúc', name: 'Làng gốm Hương Canh', price: 0),
  Destination(province: 'Vĩnh Phúc', name: 'Hồ Xạ Hương', price: 0),
  Destination(
      province: 'Vĩnh Phúc', name: 'Vườn quốc gia Tam Đảo', price: 400000),
  Destination(province: 'Vĩnh Phúc', name: 'Chùa Tây Thiên', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Chùa Phật Tích', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Đền Đô', price: 200000),
  Destination(province: 'Bắc Ninh', name: 'Hội Lim', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Đình Đình Bảng', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Chùa Dâu', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Chùa Bút Tháp', price: 300000),
  Destination(province: 'Bắc Ninh', name: 'Đền Bà chúa Kho', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Làng Đình Bảng', price: 0),
  Destination(province: 'Bắc Ninh', name: 'Làng Tranh Đông Hồ', price: 400000),
  Destination(province: 'Bắc Ninh', name: 'Làng gốm Phù Lãng', price: 500000),
  Destination(province: 'Hưng Yên', name: 'Đền Mẫu', price: 0),
  Destination(province: 'Hưng Yên', name: 'Chùa Hiến', price: 200000),
  Destination(province: 'Hưng Yên', name: 'Văn Miếu Xích Đằng', price: 300000),
  Destination(province: 'Hưng Yên', name: 'Phố Nối', price: 0),
  Destination(province: 'Hưng Yên', name: 'Đền Chử Đồng Tử', price: 0),
  Destination(
      province: 'Hưng Yên',
      name: 'Cụm di tích Đa Hòa – Dạ Trạch',
      price: 400000),
  Destination(
      province: 'Hưng Yên', name: 'Hàm Tử – Bãi Sậy, Phố Hiến', price: 0),
  Destination(province: 'Hưng Yên', name: 'Làng Nôm', price: 0),
  Destination(province: 'Hưng Yên', name: 'Đền Phương Hoàng', price: 500000),
  Destination(province: 'Hưng Yên', name: 'Hồ Bán Nguyệt', price: 1000000),
  Destination(province: 'Hà Nam', name: 'Đình đá Tiên Phong', price: 0),
  Destination(province: 'Hà Nam', name: 'Đền Lãnh Giang', price: 0),
  Destination(province: 'Hà Nam', name: 'Đền Trần Thương', price: 0),
  Destination(province: 'Hà Nam', name: 'Đền Trúc', price: 200000),
  Destination(province: 'Hà Nam', name: 'Đền Vũ Điện', price: 0),
  Destination(province: 'Hà Nam', name: 'Đền Lăng', price: 0),
  Destination(province: 'Hà Nam', name: 'Kẽm Trống', price: 0),
  Destination(province: 'Hà Nam', name: 'Bát cảnh sơn', price: 0),
  Destination(
      province: 'Hà Nam', name: 'Khu di tích văn hóa lịch sử', price: 300000),
  Destination(province: 'Hà Nam', name: 'Chùa Bà Đanh', price: 0),
  Destination(province: 'Hà Nam', name: 'Chùa Tam Trúc', price: 7000000),
  Destination(province: 'Hà Nam', name: 'Chùa Phật Quang', price: 500000),
  Destination(
      province: 'Hà Nam', name: 'Chùa Địa Tạng – Phi Lai Tự', price: 1000000),
  Destination(province: 'Thái Bình', name: 'Bãi biển Đồng Châu', price: 0),
  Destination(
      province: 'Thái Bình',
      name: 'Khu du lịch sinh thái Cồn Vành',
      price: 300000),
  Destination(
      province: 'Thái Bình',
      name: 'Khu du lịch sinh thái Cồn Đen',
      price: 40000),
  Destination(province: 'Thái Bình', name: 'Chùa Keo', price: 0),
  Destination(province: 'Thái Bình', name: 'Đền Tiên La', price: 0),
  Destination(province: 'Thái Bình', name: 'Làng vườn Bách Thuận', price: 0),
  Destination(
      province: 'Thái Bình', name: 'Làng nghề chạm bạc Đồng Xâm', price: 0),
  Destination(
      province: 'Thái Bình',
      name: 'Làng dệt khăn, dệt vải Phương La – Thái Phương',
      price: 0),
  Destination(province: 'Thái Bình', name: 'Làng dệt chiếu Hới', price: 0),
  Destination(province: 'Nam Định', name: 'Biển Quất Lâm', price: 0),
  Destination(province: 'Nam Định', name: 'Bãi tắm Thịnh Long', price: 400000),
  Destination(province: 'Nam Định', name: 'Khu di tích Phủ Dầy', price: 300000),
  Destination(
      province: 'Nam Định', name: 'Vườn quốc gia Xuân Thủy', price: 200000),
  Destination(province: 'Nam Định', name: 'Đền Trần', price: 0),
  Destination(
      province: 'Ninh Bình', name: 'Khu du lịch Tam Cốc', price: 500000),
  Destination(
      province: 'Ninh Bình', name: 'Khu di tích cố đô Hoa Lư', price: 400000),
  Destination(province: 'Ninh Bình', name: 'Nhà Thờ Phát Diện', price: 0),
  Destination(
      province: 'Ninh Bình', name: 'Khu du lịch Tràng An', price: 200000),
  Destination(province: 'Ninh Bình', name: 'Chùa Bái Đính', price: 1000000),
  Destination(
      province: 'Ninh Bình', name: 'Vườn quốc gia Cúc Phương', price: 7000000),
  Destination(province: 'Ninh Bình', name: 'Chùa Bích Động', price: 300000),
  Destination(province: 'Ninh Bình', name: 'Động Thiên Hà', price: 500000),
  Destination(
      province: 'Ninh Bình',
      name: 'Khu bảo Tồn Thiên Nhiên Vân Long',
      price: 400000),
  Destination(
      province: 'Ninh Bình', name: 'Vườn chim Thung Nham', price: 500000),
  Destination(province: 'Bắc Kạn', name: 'Hồ Ba Bể', price: 300000),
  Destination(province: 'Bắc Kạn', name: 'Vườn Quốc Gia Ba Bể', price: 200000),
  Destination(province: 'Bắc Kạn', name: 'Động Nàng Tiên', price: 50000),
  Destination(province: 'Bắc Kạn', name: 'Động Puông', price: 50000),
  Destination(province: 'Bắc Kạn', name: 'Thác Đầu Đẳng', price: 400000),
  Destination(province: 'Bắc Kạn', name: 'Chùa Thạch Long', price: 0),
  Destination(province: 'Lạng Sơn', name: 'Nàng Tô Thị', price: 0),
  Destination(province: 'Lạng Sơn', name: 'Cột cờ Phai Vê', price: 200000),
  Destination(province: 'Lạng Sơn', name: 'Thành nhà Mạc', price: 0),
  Destination(province: 'Lạng Sơn', name: 'Ải Chi Lăng', price: 400000),
  Destination(province: 'Lạng Sơn', name: 'Đền Kỳ Cùng', price: 0),
  Destination(province: 'Lạng Sơn', name: 'Đền Mẫu Đồng Đăng', price: 0),
  Destination(province: 'Lạng Sơn', name: 'Chợ Đông Kinh', price: 0),
  Destination(province: 'Lạng Sơn', name: 'Bắc Lê', price: 300000),
  Destination(province: 'Lạng Sơn', name: 'Đông Nhi Thanh', price: 500000),
  Destination(province: 'Lạng Sơn', name: 'Mẫu Sơn', price: 700000),
  Destination(province: 'Thái Nguyên', name: 'Hồ Núi Cốc', price: 200000),
  Destination(
      province: 'Thái Nguyên', name: 'Khu an toàn kháng chiến ATK', price: 0),
  Destination(
      province: 'Thái Nguyên',
      name: 'Bảo tàng dân tộc Việt Nam',
      price: 300000),
  Destination(province: 'Thái Nguyên', name: 'Thác Nậm Dứt', price: 400000),
  Destination(province: 'Thái Nguyên', name: 'Động Linh Sơn', price: 200000),
  Destination(province: 'Thái Nguyên', name: 'Suối Mỏ Gà', price: 500000),
  Destination(
      province: 'Thái Nguyên', name: 'Hang Phượng Hoàng', price: 500000),
  Destination(province: 'Thái Nguyên', name: 'Đền Đuổm', price: 0),
  Destination(province: 'Thái Nguyên', name: 'Đồi chè Tân Cương', price: 50000),
  Destination(
      province: 'Thái Nguyên',
      name: 'Hang động Đồng Hỷ - Võ Nhai',
      price: 700000),
  Destination(province: 'Bắc Giang', name: 'Khu di tích Khuôn Thần', price: 0),
  Destination(
      province: 'Bắc Giang', name: 'Rừng nguyên sinh Khe Rỗ', price: 400000),
  Destination(province: 'Bắc Giang', name: 'Đền Suối Mỡ', price: 0),
  Destination(
      province: 'Bắc Giang', name: 'Khu di tích Suối Mỡ', price: 300000),
  Destination(province: 'Bắc Giang', name: 'Chùa Đức La', price: 0),
  Destination(province: 'Bắc Giang', name: 'Đình Thổ Hà', price: 0),
  Destination(province: 'Bắc Giang', name: 'Hồ Cấm Sơn', price: 500000),
  Destination(province: 'Bắc Giang', name: 'Làng rượu Vân Hà', price: 200000),
  Destination(
      province: 'Bắc Giang', name: 'Thành cổ Xương Giang', price: 1000000),
  Destination(province: 'Phú Thọ', name: 'Khu di tích đền Hùng', price: 0),
  Destination(province: 'Phú Thọ', name: 'Đền Quốc Mẫu Âu Cơ', price: 0),
  Destination(province: 'Phú Thọ', name: 'Ao giời', price: 200000),
  Destination(province: 'Phú Thọ', name: 'Vườn quốc gia Xuân Sơn', price: 0),
  Destination(province: 'Phú Thọ', name: 'Đồi chè Long Cốc', price: 400000),
  Destination(province: 'Phú Thọ', name: 'Hang Lạng', price: 300000),
  Destination(
      province: 'Phú Thọ',
      name: 'Khu du lịch nước khoáng nóng Sơn Thủy',
      price: 500000),
  Destination(province: 'Lai Châu', name: 'Đèo Ô Quy Hồ', price: 200000),
  Destination(province: 'Lai Châu', name: 'Cao Nguyên Sìn Hồ', price: 400000),
  Destination(province: 'Lai Châu', name: 'Ngã Ba sông Đà – Nậm Na', price: 0),
  Destination(province: 'Lai Châu', name: 'Đỉnh Chu Va', price: 500000),
  Destination(province: 'Lai Châu', name: 'Cánh Đồng Mường Than', price: 0),
  Destination(
      province: 'Lai Châu',
      name: 'Núi Nam Pu Ta Leng – Phong Thổ',
      price: 1000000),
  Destination(
      province: 'Lai Châu', name: 'Pu Si Lung – Mường Tè', price: 7000000),
  Destination(
      province: 'Lai Châu', name: 'Đỉnh Tả Liên – Phong Thổ', price: 300000),
  Destination(province: 'Lào Cai', name: 'Núi Hàm Rồng', price: 200000),
  Destination(province: 'Lào Cai', name: 'Thành phố Sapa', price: 0),
  Destination(province: 'Lào Cai', name: 'Đỉnh Phanxipang', price: 500000),
  Destination(province: 'Lào Cai', name: 'Bản Tà Phìn', price: 300000),
  Destination(province: 'Lào Cai', name: 'Bản Cát Cát', price: 200000),
  Destination(province: 'Lào Cai', name: 'Swing Sapa', price: 400000),
  Destination(province: 'Lào Cai', name: 'Thung Lũng Mường Hoa', price: 200000),
  Destination(province: 'Lào Cai', name: 'Thác Bạc', price: 50000),
  Destination(province: 'Lào Cai', name: 'Cổng trời', price: 0),
  Destination(province: 'Lào Cai', name: 'Nhà thờ đá Sapa', price: 0),
  Destination(province: 'Lào Cai', name: 'Cổng San', price: 0),
  Destination(
      province: 'Điện Biên',
      name: 'Khu di tích chiến thắng Điện Biên Phủ',
      price: 0),
  Destination(province: 'Điện Biên', name: 'Thị xã Mường Thanh', price: 0),
  Destination(province: 'Điện Biên', name: 'Cầu Hang Tôm', price: 200000),
  Destination(province: 'Điện Biên', name: 'Đèo Pha Đin', price: 400000),
  Destination(province: 'Điện Biên', name: 'Hồ Pá Khoang', price: 500000),
  Destination(
      province: 'Điện Biên', name: 'Suối khoáng nóng Hua Pe', price: 300000),
  Destination(province: 'Điện Biên', name: 'Cực Tây A Pa Chải', price: 7000000),
  Destination(province: 'Yên Bái', name: 'Mù Cang Chải', price: 400000),
  Destination(province: 'Yên Bái', name: 'Xã La Pán Tẩn', price: 200000),
  Destination(province: 'Yên Bái', name: 'Suối Giàng', price: 300000),
  Destination(province: 'Yên Bái', name: 'Hồ Thác Bà', price: 500000),
  Destination(province: 'Yên Bái', name: 'Thác Pú Nhu', price: 400000),
  Destination(province: 'Yên Bái', name: 'Xã Tú Lê', price: 200000),
  Destination(province: 'Yên Bái', name: 'Bản Lìm Mông', price: 200000),
  Destination(province: 'Yên Bái', name: 'Cánh đồng Mường Lò', price: 0),
  Destination(province: 'Yên Bái', name: 'Hồ Chóp Dù', price: 700000),
  Destination(province: 'Sơn La', name: 'Hồ Chiềng Khoi', price: 200000),
  Destination(province: 'Sơn La', name: 'Bản Mòng', price: 400000),
  Destination(province: 'Sơn La', name: 'Thác Dải Yếm', price: 500000),
  Destination(province: 'Sơn La', name: 'Hồ Tiền Phong', price: 200000),
  Destination(province: 'Sơn La', name: 'Núi Pha Luông', price: 0),
  Destination(province: 'Sơn La', name: 'Thành phố Sơn La', price: 0),
  Destination(
      province: 'Sơn La', name: 'Nhà ngục Sơn La và bảo tàng Sơn La', price: 0),
  Destination(province: 'Sơn La', name: 'Cụm du lịch Sông Đà', price: 7000000),
  Destination(province: 'Sơn La', name: 'Động Sơn Mộc Hương', price: 500000),
  Destination(province: 'Sơn La', name: 'Mộc Châu', price: 300000),
  Destination(
      province: 'Hòa Bình', name: 'Lũng Vân – Nóc nhà xứ Mường', price: 300000),
  Destination(province: 'Hòa Bình', name: 'Cửu thác Tú Sơn', price: 400000),
  Destination(
      province: 'Hòa Bình', name: 'Nhà máy thủy điện Hòa Bình', price: 0),
  Destination(
      province: 'Hòa Bình',
      name: 'Thung Nai – Hạ Long trên cạn',
      price: 500000),
  Destination(
      province: 'Hòa Bình',
      name: 'Mai Châu – Vùng đất thơ mộng',
      price: 200000),
  Destination(province: 'Hòa Bình', name: 'Động Thác Đá', price: 400000),
  Destination(
      province: 'Hòa Bình',
      name: 'Khu du lịch thác Thăng Thiên',
      price: 500000),
  Destination(province: 'Hòa Bình', name: 'Động Hoa Tiên', price: 300000),
  Destination(province: 'Hòa Bình', name: 'Động Thác Bờ', price: 200000),
];
